# Generated by Django 5.2.4 on 2025-08-30 11:04

import ads.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_alter_ad_options_ad_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(default=ads.models.generate_room_code, max_length=6, unique=True)),
                ('name', models.CharField(default='Spin Challenge Room', max_length=100)),
                ('max_players', models.IntegerField(default=6)),
                ('current_players', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now)),
                ('wheel_theme', models.CharField(default='classic', max_length=20)),
                ('challenge_type', models.CharField(default='truth-dare', max_length=50)),
            ],
            options={
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('is_ready', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='ads.room')),
            ],
            options={
                'ordering': ['joined_at'],
            },
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_text', models.TextField()),
                ('challenge_type', models.CharField(max_length=50)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ads.player')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='ads.room')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
