# Generated by Django 5.2.4 on 2025-08-30 11:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_room_player_challenge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['turn_order', 'joined_at']},
        ),
        migrations.AddField(
            model_name='challenge',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_challenges', to='ads.player'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='is_room_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='turn_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='current_round',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='room',
            name='current_turn',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='game_started',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='total_rounds',
            field=models.IntegerField(default=5),
        ),
        migrations.CreateModel(
            name='GameRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('current_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ads.player')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='ads.room')),
            ],
            options={
                'ordering': ['round_number'],
            },
        ),
    ]
